version: "3.8"
services:
  api:
    # image: node:14
    build: ./api
    container_name: api_c
    volumes:
      - ./api:/app
      - ./app/node_modules
    # working_dir: /app
    # command: npm run dev
    ports:
      - '4000:4000'
    # depends_on:
    #   - db
  # db:
  #   image: postgres:14
  #   volumes:
  #     - ./data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres